ARG BASE_IMAGE

FROM ${BASE_IMAGE}

SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND noninteractive

RUN apt update -q -qq && \
    apt install -q -qq -y apt-utils mesa-utils less x11-xserver-utils x11-utils && \
    apt upgrade -q -qq -y && \
    apt autoremove -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/
