version: "2.3"
services:
  xserver:
    image: devrt/xserver
    ipc: host
    security_opt:
      - seccomp:unconfined
    ports:
      - "3000:80"
    environment:
      - DISPLAY=:1
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X1"]
      interval: "1s"
      retries: 20
  simulator:
    image: your_docker_image ## ADD your image name
    ipc: host
    network_mode: host
    security_opt:
      - seccomp:unconfined
    environment:
      - DISPLAY=:1
#      - ROS_HOSTNAME=localhost
    volumes_from:
      - xserver
    depends_on:
      - xserver
