version: "2.3"
services:
  xserver:
    image: devrt/xserver
    ipc: host
    security_opt:
      - seccomp:unconfined
    ports:
      - "3000:80"
    environment:
      - DISPLAY=:1
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X1"]
      interval: "1s"
      retries: 20
  simulator:
    image: your_docker_image_nvidia ## ADD your image name
    ipc: host
    network_mode: host
    security_opt:
      - seccomp:unconfined
    runtime: nvidia
    environment:
      - DISPLAY=:1
      - VGL_DISPLAY=:0 ## naitive display (running opengl)
#      - DOCKER_ROS_SETUP=/catkin_ws/devel/setup.bash
#      - DOCKER_ROS_IP=localhost
#      - DOCKER_ROS_MASTER_URI=http://localhost:11311
    volumes:
      - /tmp/.X11-unix/X0:/tmp/.X11-unix/X0
    volumes_from:
      - xserver
    depends_on:
      - xserver
