## before running: xhost +si:localuser:root
## after running: xhost -local:root
version: "2.3"
services:
  xserver:
    image: devrt/xserver
    ipc: host
    security_opt:
      - seccomp:unconfined
    ports:
      - "3000:80"
    environment:
      - DISPLAY=:1
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X1"]
      interval: "1s"
      retries: 20
  main:
    image: ___image_name___
    ipc: host
    network_mode: host
    security_opt:
      - seccomp:unconfined
    runtime: nvidia
    #command: // should be set at supervisord.conf
    #command: [bash, -c, 'while true; do sleep 5; done'] ##for debug
    #command: [ /entrypoint_xserver.sh, roslaunch, target_pkg, target.launch ]
    #command:___command___
    environment:
      - DISPLAY=:1
      - VGL_DISPLAY=:0 ## naitive display (running opengl)
######- ___extra-environment-variables___
      # - DOCKER_ROS_SETUP=/catkin_ws/devel/setup.bash
      # - ROS_MASTER_URI=http://localhost:11311
      # - ROS_IP=localhost
      # - ROS_HOSTNAME=localhost
      # - ROS_HOME=/ros_home
    volumes:
      - /tmp/.X11-unix/X0:/tmp/.X11-unix/X0
      - '___user_directory___:/userdir'
    volumes_from:
      - xserver
    depends_on:
      - xserver
